apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapps-io-cms
  namespace: default
  labels:
    app: tapps-io-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapps-io-cms
  template:
    metadata:
      labels:
        app: tapps-io-cms
    spec:
      containers:
        - name: tapps-io-cms
          image: tapps/tapps-io.cms:$VERSION
          ports:
            - containerPort: 1337
              name: cms
          env:
            - name: HOST
              value: "https://content.tapps.io"

            - name: DATABASE_CLIENT
              value: "postgres"

            - name: DATABASE_HOST
              value: "external-postgresql"

            - name: DATABASE_PORT
              value: "25060"

            - name: DATABASE_SSL
              value: "true"

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: external-postgresql-strapi
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-postgresql-strapi
                  key: password
